"""
HC-XCDSS Patient AI Context Builder

Builds clean, sanitized, and deterministic context from structured analysis reports
for the patient-facing AI assistant. Excludes raw filesystem paths and internal state.
"""

from typing import Any, Dict, List, Optional


def build_patient_ai_context(report: Dict[str, Any]) -> Dict[str, Any]:
    """
    Constructs a safe, self-contained AI context payload derived strictly from
    the structured Report Engine output.

    Args:
        report: The structured report dictionary generated by Report Engine.

    Returns:
        Sanitized context dictionary structured for prompt construction / LLM ingestion.
    """
    analysis_id: Optional[str] = report.get("analysis_id")
    created_at: Optional[str] = report.get("created_at")
    view: str = report.get("view", "Frontal")
    total_evaluated: int = report.get("total_evaluated", 0)
    total_detected: int = report.get("total_detected", 0)
    overall_summary: str = report.get("overall_summary", "")

    # Extract clean detected findings details
    detected_findings_data = report.get("findings_detected", [])
    detected_findings_summary: List[Dict[str, Any]] = []

    for det in detected_findings_data:
        name = det.get("name")
        prob = det.get("probability")
        thresh = det.get("threshold")
        has_heatmap = bool(det.get("heatmap"))
        expl = det.get("explanation") or {}

        entry = {
            "finding": name,
            "probability": prob,
            "threshold": thresh,
            "gradcam_available": has_heatmap,
            "title": expl.get("title", name),
            "simple_explanation": expl.get("simple_explanation"),
            "what_it_means": expl.get("what_it_means"),
            "possible_causes": expl.get("possible_causes", []),
            "important_note": expl.get("important_note"),
        }
        detected_findings_summary.append(entry)

    # Extract clean evaluated findings list (name, probability, threshold, detected)
    evaluated_findings_data = report.get("findings_evaluated", [])
    evaluated_findings_summary: List[Dict[str, Any]] = [
        {
            "finding": ef.get("name"),
            "probability": ef.get("probability"),
            "threshold": ef.get("threshold"),
            "detected": ef.get("detected", False),
        }
        for ef in evaluated_findings_data
    ]

    # Patient-friendly interpretation
    patient_interp = report.get("patient_interpretation", {})

    # Explainability metadata
    explainability_info = report.get("explainability", {})
    gradcam_available_findings = explainability_info.get("visualizations_available", [])

    # Clinical limitations
    clinical_disclaimer = report.get("clinical_disclaimer", {})

    return {
        "analysis_id": analysis_id,
        "created_at": created_at,
        "view": view,
        "summary": overall_summary,
        "findings_detected_count": total_detected,
        "findings_evaluated_count": total_evaluated,
        "detected_findings": detected_findings_summary,
        "all_evaluated_findings": evaluated_findings_summary,
        "patient_interpretation": {
            "headline": patient_interp.get("headline", ""),
            "details": patient_interp.get("details", ""),
        },
        "explainability": {
            "method": explainability_info.get("method", "Grad-CAM"),
            "description": explainability_info.get("description", ""),
            "available_visualizations": gradcam_available_findings,
        },
        "clinical_disclaimer": clinical_disclaimer.get("disclaimer", ""),
        "important_limitations": [
            "HC-XCDSS provides decision-support observations, not medical diagnoses.",
            "AI predictions are probabilistic and must be clinically correlated with patient history and physical examination.",
            "Visual heatmaps (Grad-CAM) indicate model attention regions and do not represent tissue pathology.",
            "No medical treatments or prescription changes should be made based on AI output alone.",
        ],
    }
